language: java
jdk:
  - openjdk8

branches:
  only:
  - master

cache:
  - directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'


script: "./gradlew clean build"

notifications:
  slack:
    rooms:
    - godngu:HmHsInvDy7lJclT9mkU9I7sx#study

before_deploy:
  - zip -r springboot-webservice *
  - mkdir -p deploy
  - mv springboot-webservice.zip deploy/springboot-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-webservice-deploy-kil
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: godngu/springboot-webservice
      branch: master
    local_dir: deploy

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-webservice-deploy-kil
    key: springboot-webservice.zip
    bundle_type: zip
    application: springboot-webservice
    deployment_group: springboot-webservice-group
    region: ap-northeast-2
    wait-unitl-deployed: true
    on:
      repo: godngu/springboot-webservice
      branch: master
